<a href="https://colab.research.google.com/github/General2096/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


'''
Introduction to tensors

Pytorch tensors are created using torch.Tensor() = https://pytorch.org/docs/stable/tensors.html
'''

In [4]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
#Get tensor back as python int

In [7]:
scalar.item()

7

In [8]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [12]:
#m MATRIX
MATRIX = torch.tensor(([7,8], [9,10]))
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX[0]

tensor([7, 8])

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])

In [23]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

#### Random Tensors

Why random tensors?

Random tensors are important because they way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with Random numbers -> loof at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html?highlight=torch+rand#torch.rand


In [5]:
#Create a random tensors of (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8192, 0.2970, 0.0855, 0.4330],
        [0.5818, 0.6723, 0.9331, 0.4254],
        [0.4471, 0.5452, 0.4356, 0.5537]])

In [7]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tesnor = torch.rand(size = (224,224,3)) #height, width, color channels (RGB)
random_image_size_tesnor.shape, random_image_size_tesnor.ndim

(torch.Size([224, 224, 3]), 3)

In [8]:
torch.rand(size = (3,3))

tensor([[0.2981, 0.5490, 0.4269],
        [0.5815, 0.3587, 0.2474],
        [0.6204, 0.2619, 0.6544]])

### Zeros and Ones

In [9]:
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [11]:
#create a tensor of all ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors like

In [16]:
one_to_ten = torch.arange(start = 0, end = 1000, step = 7)
one_to_ten

tensor([  0,   7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84,  91,
         98, 105, 112, 119, 126, 133, 140, 147, 154, 161, 168, 175, 182, 189,
        196, 203, 210, 217, 224, 231, 238, 245, 252, 259, 266, 273, 280, 287,
        294, 301, 308, 315, 322, 329, 336, 343, 350, 357, 364, 371, 378, 385,
        392, 399, 406, 413, 420, 427, 434, 441, 448, 455, 462, 469, 476, 483,
        490, 497, 504, 511, 518, 525, 532, 539, 546, 553, 560, 567, 574, 581,
        588, 595, 602, 609, 616, 623, 630, 637, 644, 651, 658, 665, 672, 679,
        686, 693, 700, 707, 714, 721, 728, 735, 742, 749, 756, 763, 770, 777,
        784, 791, 798, 805, 812, 819, 826, 833, 840, 847, 854, 861, 868, 875,
        882, 889, 896, 903, 910, 917, 924, 931, 938, 945, 952, 959, 966, 973,
        980, 987, 994])

In [20]:
#create tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor data types

**Note:** tensor datatypes is one of the big 3 erors you'll erun into with Pytorch and deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [27]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None, #what data type is the tensor (e.g. float 32(one precision) or float 16(half precision), associated with computer memory, faster calculation with 16)
                               device = None, #What device is your tensor on
                               requires_grad = False) #whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [24]:
float_32_tensor.dtype

torch.float16

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [30]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [31]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

    Tensors not right datatype - to do get datatype from a tensor, use 'tensor.dtype'
    Tensors not right shape - to get shape from a tensor, can use 'tensor.shape'
    Tensors not on the right device - to get device from a tensor, can use 'tensor.device'


In [32]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4416, 0.6707, 0.1720, 0.9832],
        [0.1112, 0.1151, 0.4570, 0.7218],
        [0.9531, 0.0509, 0.8520, 0.1886]])

In [36]:
#Find out detailes about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor is on: {some_tensor.device}")

tensor([[0.4416, 0.6707, 0.1720, 0.9832],
        [0.1112, 0.1151, 0.4570, 0.7218],
        [0.9531, 0.0509, 0.8520, 0.1886]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor is on: cpu
